#!/bin/sh

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-${GLITE_LOCATION}/var}

[ -f /etc/glite.conf ] && . /etc/glite.conf
[ -f $GLITE_LOCATION/etc/glite-wms.conf ] && . $GLITE_LOCATION/etc/glite-wms.conf

[ -f $GLITE_LOCATION/etc/jp.conf ] && . $GLITE_LOCATION/etc/jp.conf
[ -f $GLITE_LOCATION_VAR/etc/jp.conf ] && . $GLITE_LOCATION_VAR/etc/jp.conf

[ -f $HOME/.glite.conf ] && . $HOME/.glite.conf

[ -n "$GLITE_JP_PRIMARY_PIDFILE" ] && pidfile=$GLITE_JP_PRIMARY_PIDFILE ||
	pidfile="$GLITE_LOCATION_VAR/glite-jp-primarystoraged.pid"

unset creds

test -n "$GLITE_JP_PRIMARY_PORT" ||  GLITE_JP_PRIMARY_PORT=8901

start()
{
	if test -z "$GLITE_USER" ;then
		echo 'Error: GLITE_USER is not set'
		echo FAILED
		return 1
	fi
	if test -z "$GLOBUS_LOCATION" ;then
		echo 'Error: GLOBUS_LOCATION is not set'
		echo FAILED
		return 1
	fi
	if test -z "$GLITE_JP_PRIMARY_PEERS" ;then
		echo 'Error: incomplete configuration (GLITE_JP_PRIMARY_PEERS is not set)'
		echo FAILED
		return 1
	fi
	if test -z "$GLITE_JP_PRIMARY_FTP_PORT" -o \
		-z "$GLITE_JP_PRIMARY_INTERNAL" -o -z "$GLITE_JP_PRIMARY_EXTERNAL" ;then
		echo 'Error: incomplete configuration (GLITE_JP_PRIMARY_FTP_PORT,' \
			'GLITE_JP_PRIMARY_INTERNAL, or GLITE_JP_PRIMARY_EXTERNAL is not set)'
		echo FAILED
		return 1
	fi

	if [ -n "$GLITE_HOST_CERT" -a -n "$GLITE_HOST_KEY" ] ;then
		creds="-c '$GLITE_HOST_CERT' -k '$GLITE_HOST_KEY'"
		X509_USER_CERT="$GLITE_HOST_CERT"
		X509_USER_KEY="$GLITE_HOST_KEY"
	fi

	if test -z "$creds"; then
		if su - $GLITE_USER -c "test -r /etc/grid-security/hostkey.pem -a -r /etc/grid-security/hostcert.pem"; then
			echo "$0: WARNING: /etc/grid-security/hostkey.pem readable by $GLITE_USER"
			creds="-c /etc/grid-security/hostcert.pem -k /etc/grid-security/hostkey.pem"
			X509_USER_CERT=/etc/grid-security/hostcert.pem
			X509_USER_KEY=/etc/grid-security/hostkey.pem
		fi
	fi


	[ -z "$creds" ] && echo $0: WARNING: No credentials specified. Using default lookup which is dangerous. >&2

	unset GLITE_JP_PRIMARY_DBCS_OPTION
	if test -n "$GLITE_JP_PRIMARY_DBCS"; then
		GLITE_JP_PRIMARY_DBCS_OPTION="-BD,'$GLITE_JP_PRIMARY_DBCS'"
	fi

	echo -n Starting glite-jp-primarystoraged ...
	su - $GLITE_USER -c "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GLOBUS_LOCATION/lib:$GLITE_LOCATION/lib \
		$GLITE_LOCATION/bin/glite-jp-primarystoraged \
		$GLITE_JP_DEBUG \
		-P $GLITE_LOCATION/lib/glite_lb_plugin.so -P $GLITE_LOCATION/lib/glite-jp-sandbox.so \
		$creds -a '$GLITE_JP_PRIMARY_PEERS' \
		-i '$pidfile' -p $GLITE_JP_PRIMARY_PORT $GLITE_JP_PRIMARY_SPECIAL \
		-BI,'$GLITE_JP_PRIMARY_INTERNAL' -BE,'$GLITE_JP_PRIMARY_EXTERNAL' \
		${GLITE_JP_PRIMARY_DBCS_OPTION} " && echo " done"
	if [ $? != 0 ]; then
		echo " FAILED"
		return 1
	fi

	echo -n Starting JP gridftp server ...
	su - $GLITE_USER -c "X509_USER_CERT=\"$X509_USER_CERT\" \
                X509_USER_KEY=\"$X509_USER_KEY\" \
                GLITE_USER=\"$GLITE_USER\" \
                FTPBE_INT_PREFIX=\"$GLITE_JP_PRIMARY_INTERNAL\" \
                LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GLOBUS_LOCATION/lib:$GLITE_LOCATION/lib \
		FTPBE_DB_CS=$GLITE_JP_PRIMARY_DBCS \
		GSI_AUTHZ_CONF=$GLITE_JP_GSI_AUTHZ \
		$GLOBUS_LOCATION/sbin/globus-gridftp-server -debug -s -p $GLITE_JP_PRIMARY_FTP_PORT & \
		pid=\$!; echo \$pid > $pidfile.ftpd; sleep 2; true kill -0 \$pid" && echo " done" || echo " FAILED"
}

stop()
{
	if [ -f "$pidfile" ]; then
		pid=`cat "$pidfile"`
		kill $pid
		echo -n Stopping glite-jp-primarystoraged \($pid\) ...
		try=0
		while ps p $pid >/dev/null 2>&1; do 
			sleep 1;
			try=`expr $try + 1`
			if [ $try = 20 ]; then
				echo " giving up after $try retries"
				return 1
			fi
	 	done
		kill -9 $pid >/dev/null 2>&1
		echo " done"
		rm -f "$pidfile"
	else
		echo "$pidfile" does not exist - glite-jp-primarystoraged not running? >&2
		return 1
	fi
	if [ -f "$pidfile.ftpd" ]; then
		pid=`cat "$pidfile.ftpd"`
		kill $pid
		echo -n Stopping JP ftp server \($pid\) ...
		try=0
		while ps p $pid >/dev/null 2>&1; do 
			sleep 1;
			try=`expr $try + 1`
			if [ $try = 20 ]; then
				echo " giving up after $try retries"
				return 1
			fi
	 	done
		kill -9 $pid >/dev/null 2>&1
		echo " done"
		rm -f "$pidfile.ftpd"
	else
		echo "$pidfile.ftpd" does not exist - JP ftp server not running? >&2
		return 1
	fi

	return 0
}

status()
{
	retval=0
	# XXX pidfile?
        if netstat -an --inet | grep "^tcp .* 0.0.0.0:${GLITE_JP_PRIMARY_PORT} .*LISTEN" >/dev/null 2>&1 ;then
        echo glite-jp-primarystoraged running 
        else
        echo glite-jp-primarystoraged not running
        retval=1
        fi

        if netstat -an --inet | grep "^tcp .* 0.0.0.0:${GLITE_JP_PRIMARY_FTP_PORT} .*LISTEN" >/dev/null 2>&1 ;then
        echo JP gridftp server running 
        else
        echo JP gridftp server not running
        retval=1
        fi

	return $retval
}

case x$1 in
	xstart)	start;;
	xstop)	stop;;
	xrestart) stop; start;;
	xstatus) status;;
	x*)	echo usage: $0 start,stop,restart,status >&2
		exit 1;;
esac
