#!/bin/sh

cd ../..

cvs co org.glite
cvs co org.glite.jp
                                                                                                                                                             
cd org.glite.jp/project
ant -f glite.jp.csf.xml

